name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up C++ environment
    - name: Install OpenCL
      run: |
        sudo apt-get update
        sudo apt-get install -y ocl-icd-opencl-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build C++
      run: cmake --build ${{github.workspace}}/build --config Release

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest pybind11

    # Build and install Python package
    - name: Build Python package
      run: |
        cd python_module
        pip install -e .

    # Run tests
    - name: Run C++ tests
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f risma_cpp ]; then
          ./risma_cpp
        fi

    - name: Run Python tests
      run: |
        cd python_module
        python -c "from risma.core import Portfolio, RiskCalculator; p = Portfolio(); rc = RiskCalculator(); print('Import test successful')" 